config/routes.rb
Restaurant::Application.routes.draw do
  resources :home do
    collection do
      post 'search'
    end
    member do
      get 'location'
      get 'city'
      get 'food'
      post 'comment'
    end
  end

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  root 'home#index'

end

app/models/city.rb
class City < ActiveRecord::Base

  # Association With RestroAddress
  has_many :restro_addresses

end

app/models/food.rb
class Food < ActiveRecord::Base

  # Association With Restro & RestroFood
  has_many :restro_foods
  has_many :restros, through: :restro_foods
end

app/models/location.rb
class Location < ActiveRecord::Base

  # Association With RestroAddress
  has_many :restro_addresses
end

app/models/rating.rb
class Rating < ActiveRecord::Base

  #Association With User
  belongs_to :user
  #Association With Restro
  belongs_to :restro
end

app/models/restro.rb
class Restro < ActiveRecord::Base


  # Association With RestroAddress
  has_one :restro_address

  # Association With Food & RestroFood
  has_many :restro_foods
  has_many :foods, through: :restro_foods

  #Association With Ratings & User
  has_many :ratings
  has_many :users, through: :ratings

end

app/models/restro_address.rb
class RestroAddress < ActiveRecord::Base

  # Association With Restro
  belongs_to :restro

  # Association With Location
  belongs_to :location

  # Association With City
  belongs_to :city
end

app/models/restro_food.rb
class RestroFood < ActiveRecord::Base

  # Association With Restro
  belongs_to :restro
  # Association With Food
  belongs_to :food
end

app/models/user.rb
class User < ActiveRecord::Base

  #Association With Ratings & Restro
  has_many :ratings
  has_many :restros, through: :ratings

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end


  def search
    @search = params[:search]
    @restro = Restro.where("name ilike ?", "%#{params[:search]}%")
  end

  def show
    @restro = Restro.find params[:id]
    #rating = @restro.ratings.sum(:rating)
    # render :text => rating and return
  end

  def location
    @location = Location.find params[:id]
  end

  def food
    @food = Food.find params[:id]
  end

  def city
    @city = City.find params[:id]
  end

  def comment
    @restro = Restro.find params[:id]
    Rating.create(
        :comment => params[:message],
        :rating => params[:rating].to_i,
        :restro_id => @restro.id,
        :user_id => current_user.id
    )

    render  :action => 'show' ,:id => @restro.id
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/city.html.erb
<%= render :partial => "shared/header" %>

<h1>Restaurants in <%= @city.name %></h1>

<% @city.restro_addresses.each do |addr| %>
    <%= link_to addr.restro.name, home_path(addr.restro.id) %><br/>
    <%= addr.location.name %> &nbsp;&nbsp; > &nbsp;&nbsp; <%= addr.addr %>, <%= link_to addr.city.name, city_home_path(addr.city.id) %><br/>
    <% addr.restro.foods.each do |food| %>
        <%= link_to food.name, food_home_path(food.id) %>    &nbsp;&nbsp;
    <% end %>
    <br/><br/>
<% end %>

app/views/home/food.html.erb
<%= render :partial => "shared/header" %>

<h1> <%= @food.name %> Restaurants</h1>

<% @food.restros.each do |restaurant| %>
    <%= link_to restaurant.name, home_path(restaurant.id) %><br/>
    <%= link_to restaurant.restro_address.location.name, location_home_path(restaurant.restro_address.location.id) %>
    &nbsp;&nbsp; > &nbsp;&nbsp; <%= restaurant.restro_address.addr %>, <%= link_to restaurant.restro_address.city.name, city_home_path(restaurant.restro_address.city.id) %><br/>
    <% restaurant.foods.each do |food| %>
        <%= link_to food.name, food_home_path(food.id) %> &nbsp;&nbsp; &nbsp;&nbsp;
    <% end %>
    <br/><br/>
<% end %>

app/views/home/index.html.erb
<h1>Browse restaurants</h1>
<div>
<span>search restaurants</span>
  <%= render :partial => "shared/header" %>
</div>

app/views/home/location.html.erb
<%= render :partial => "shared/header" %>
<h3><%= @location.name %>'s Restaurant</h3>
<br/>

<% @location.restro_addresses.each do |addr| %>
    <%= link_to addr.restro.name, home_path(addr.restro.id) %><br/>
    <%= @location.name %> &nbsp;&nbsp; > &nbsp;&nbsp; <%= addr.addr %>, <%= link_to addr.city.name, city_home_path(addr.city.id) %><br/>
    <% addr.restro.foods.each do |food| %>
        <%= link_to food.name, food_home_path(food.id) %>    &nbsp;&nbsp;
    <% end %>
    <br/><br/>
<% end %>

app/views/home/search.html.erb
<%= render :partial => "shared/header" %>

<h1>Restaurants in Delhi NCR matching "<%= @search %>"</h1>

<table>
  <tr>
    <th>Restaurant Name</th>
    <th>Location</th>
    <th>Menu</th>
    <th>Address</th>
    <th>City</th>
  </tr>
  <% unless @restro.nil? %>
      <% @restro.each do |restaurant| %>
          <tr>
            <td><%= link_to restaurant.name, home_path(restaurant.id) %></td>
            <td><%= link_to restaurant.restro_address.location.name, location_home_path(restaurant.restro_address.location.id) %></td>
            <td>
              <% restaurant.foods.each do |food| %>
                  <%= link_to food.name, food_home_path(food.id) %>
              <% end %>
            </td>
            <td><%= restaurant.restro_address.addr %></td>
            <td><%= link_to restaurant.restro_address.city.name, city_home_path(restaurant.restro_address.city.id) %></td>
          </tr>
      <% end %>
  <% else %>
      <tr>
        <td></td>
        <td></td>
        <td>No Record Found.</td>
        <td></td>
        <td></td>
      </tr>

  <% end %>

</table>

app/views/home/show.html.erb
<%= render :partial => "shared/header" %>

<h3><%= @restro.name %></h3>
<h5>Rating :  <%= sprintf("%.2f", @restro.ratings.sum(:rating).to_f/@restro.ratings.count.to_f) unless @restro.ratings.count == 0 %> </h5>
<%= link_to @restro.restro_address.location.name, location_home_path(@restro.restro_address.location.id) %> &nbsp;&nbsp; >
<% @restro.foods.each do |food| %>
    &nbsp; &nbsp;<%= link_to food.name, food_home_path(food.id) %>
<% end %>
<br/> <br/>
<%= @restro.restro_address.addr %>,
<%= link_to @restro.restro_address.city.name, city_home_path(@restro.restro_address.city.id)  %>

<hr/> <br/>

<%= render :partial => 'shared/comments' %>

<%= render :partial => 'shared/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user-widget">
  <% if current_user %>
      Welcome <strong><%= current_user.name %></strong>!
      <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
      <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  <% end %>
</div>
<%= yield %>

</body>
</html>

app/views/shared/_comments.html.erb
<% @restro.ratings.each do |rating| %>
    <div class="comments">
      <b>Posted <%= time_ago_in_words(rating.created_at) %> ago by</b>
      <%= rating.user.name%><br/>
      Comment : &nbsp; <%= rating.comment %><br/>
      Rating: &nbsp; <%= rating.rating %><br/><br/>
    </div>
<% end %>

app/views/shared/_form.html.erb
<% unless current_user.nil? %>
    <h2>Share your Comments</h2>

    <div id="flash_error" style="color:red;display:none"></div>  <br/>

    <%= form_tag comment_home_path(:id => @restro.id) do %>
        <%= label_tag(:message, "How do you like this Restaurant ?") %><br />
        <%= text_area_tag(:message, nil , :onkeyup=>"countChar(this, 160)") %><br />
        <%= label_tag :rating%>
        <%= select_tag :rating,options_for_select(1..5) %>
        <br/><br/>
        <%= submit_tag("Share your Review", :id => "post") %>
    <% end %>
<% end %>

app/views/shared/_header.html.erb
<div>
  <%= form_tag search_home_index_path do %>
      <%= text_field_tag :search, nil, :placeholder => "Search Restaurant" %>
      <%= submit_tag "Go" %>
  <% end %>
</div>